<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Energistics.Etp</RootNamespace>
    <AssemblyName>ETP.DevKit.UnitTest</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ext\etp.net\src\ETP.Messages\ETP.Messages.csproj" />
    <ProjectReference Include="..\DevKit\DevKit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="v12\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Apache.Avro" Version="1.12.0" />
    <PackageReference Include="log4net" Version="3.1.0" />
    <PackageReference Include="Microsoft.VisualStudio.UnitTesting" Version="11.0.50727.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>
</Project>