<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <RootNamespace>Energistics.Etp</RootNamespace>
    <AssemblyName>ETP.DevKit</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="SuperSocket.ClientEngine.Core" Version="0.10.0" />
    <PackageReference Include="SuperWebSocket" Version="0.9.0.2" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.7" />
    <PackageReference Include="WebSocket4Net" Version="0.15.2" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ext\etp.net\src\ETP.Messages\ETP.Messages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>