<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>

    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <OutputType>Library</OutputType>
    <RootNamespace>Energistics.Etp</RootNamespace>
    <AssemblyName>ETP.DevKit</AssemblyName>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Net" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ext\etp.net\src\ETP.Messages\ETP.Messages.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Apache.Avro" Version="1.12.0" />
    <PackageReference Include="log4net" Version="3.1.0" />
    <PackageReference Include="Microsoft.Bcl" Version="1.1.10" />
    <PackageReference Include="Microsoft.Bcl.Async" Version="1.0.168" />
    <PackageReference Include="Microsoft.Bcl.Build" Version="1.0.21" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="SuperSocket.ClientEngine.Core" Version="0.10.0" />
    <PackageReference Include="SuperWebSocket" Version="0.9.0.2" />
    <PackageReference Include="WebSocket4Net" Version="0.15.2" />
  </ItemGroup>
</Project>