//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energistics.DataAccess.WITSML131.WMLP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.witsml.org/wsdl/120", ConfigurationName= "Energistics.DataAccess.WITSML131.WMLP.WMLP")]
    public interface IWMLP
    {
        
        // CODEGEN: Создание контракта сообщения, так как пространство имен упаковщика (http://www.witsml.org/message/120) сообщения WMLP_GetBaseMsgRequest не соответствует значению по умолчанию (http://www.witsml.org/wsdl/120).
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Publish.WMLP_GetBaseMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_GetBaseMsgResponse WMLP_GetBaseMsg(Energistics.DataAccess.WITSML131.WMLP.WMLP_GetBaseMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Publish.WMLP_GetCap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_GetCapResponse WMLP_GetCap(Energistics.DataAccess.WITSML131.WMLP.WMLP_GetCapRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как пространство имен упаковщика (http://www.witsml.org/message/120) сообщения WMLP_GetVersionRequest не соответствует значению по умолчанию (http://www.witsml.org/wsdl/120).
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Publish.WMLP_GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_GetVersionResponse WMLP_GetVersion(Energistics.DataAccess.WITSML131.WMLP.WMLP_GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Publish.WMLP_Subscribe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_SubscribeResponse WMLP_Subscribe(Energistics.DataAccess.WITSML131.WMLP.WMLP_SubscribeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_GetBaseMsg", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_GetBaseMsgRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short ReturnValueIn;
        
        public WMLP_GetBaseMsgRequest()
        {
        }
        
        public WMLP_GetBaseMsgRequest(short ReturnValueIn)
        {
            this.ReturnValueIn = ReturnValueIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_GetBaseMsgResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_GetBaseMsgResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public WMLP_GetBaseMsgResponse()
        {
        }
        
        public WMLP_GetBaseMsgResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_GetCap", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_GetCapRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string OptionsIn;
        
        public WMLP_GetCapRequest()
        {
        }
        
        public WMLP_GetCapRequest(string OptionsIn)
        {
            this.OptionsIn = OptionsIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_GetCapResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_GetCapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CapabilitiesOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SuppMsgOut;
        
        public WMLP_GetCapResponse()
        {
        }
        
        public WMLP_GetCapResponse(short Result, string CapabilitiesOut, string SuppMsgOut)
        {
            this.Result = Result;
            this.CapabilitiesOut = CapabilitiesOut;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_GetVersion", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_GetVersionRequest
    {
        
        public WMLP_GetVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_GetVersionResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public WMLP_GetVersionResponse()
        {
        }
        
        public WMLP_GetVersionResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_Subscribe", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_SubscribeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string SubscriptionIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string CapabilitiesIn;
        
        public WMLP_SubscribeRequest()
        {
        }
        
        public WMLP_SubscribeRequest(string SubscriptionIn, string OptionsIn, string CapabilitiesIn)
        {
            this.SubscriptionIn = SubscriptionIn;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLP_SubscribeResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLP_SubscribeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SubscriptionOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SuppMsgOut;
        
        public WMLP_SubscribeResponse()
        {
        }
        
        public WMLP_SubscribeResponse(short Result, string SubscriptionOut, string SuppMsgOut)
        {
            this.Result = Result;
            this.SubscriptionOut = SubscriptionOut;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface PublishSoapPortChannel : Energistics.DataAccess.WITSML131.WMLP.IWMLP, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WMLP : System.ServiceModel.ClientBase<Energistics.DataAccess.WITSML131.WMLP.IWMLP>, Energistics.DataAccess.WITSML131.WMLP.IWMLP
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WMLP() : 
                base(WMLP.GetDefaultBinding(), WMLP.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WMLP.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLP(EndpointConfiguration endpointConfiguration) : 
                base(WMLP.GetBindingForEndpoint(endpointConfiguration), WMLP.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLP(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WMLP.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLP(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WMLP.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLP(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_GetBaseMsgResponse Energistics.DataAccess.WITSML131.WMLP.IWMLP.WMLP_GetBaseMsg(Energistics.DataAccess.WITSML131.WMLP.WMLP_GetBaseMsgRequest request)
        {
            return base.Channel.WMLP_GetBaseMsg(request);
        }
        
        public string WMLP_GetBaseMsg(short ReturnValueIn)
        {
            Energistics.DataAccess.WITSML131.WMLP.WMLP_GetBaseMsgRequest inValue = new Energistics.DataAccess.WITSML131.WMLP.WMLP_GetBaseMsgRequest();
            inValue.ReturnValueIn = ReturnValueIn;
            Energistics.DataAccess.WITSML131.WMLP.WMLP_GetBaseMsgResponse retVal = ((Energistics.DataAccess.WITSML131.WMLP.IWMLP)(this)).WMLP_GetBaseMsg(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_GetCapResponse Energistics.DataAccess.WITSML131.WMLP.IWMLP.WMLP_GetCap(Energistics.DataAccess.WITSML131.WMLP.WMLP_GetCapRequest request)
        {
            return base.Channel.WMLP_GetCap(request);
        }
        
        public short WMLP_GetCap(string OptionsIn, out string CapabilitiesOut, out string SuppMsgOut)
        {
            Energistics.DataAccess.WITSML131.WMLP.WMLP_GetCapRequest inValue = new Energistics.DataAccess.WITSML131.WMLP.WMLP_GetCapRequest();
            inValue.OptionsIn = OptionsIn;
            Energistics.DataAccess.WITSML131.WMLP.WMLP_GetCapResponse retVal = ((Energistics.DataAccess.WITSML131.WMLP.IWMLP)(this)).WMLP_GetCap(inValue);
            CapabilitiesOut = retVal.CapabilitiesOut;
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_GetVersionResponse Energistics.DataAccess.WITSML131.WMLP.IWMLP.WMLP_GetVersion(Energistics.DataAccess.WITSML131.WMLP.WMLP_GetVersionRequest request)
        {
            return base.Channel.WMLP_GetVersion(request);
        }
        
        public string WMLP_GetVersion()
        {
            Energistics.DataAccess.WITSML131.WMLP.WMLP_GetVersionRequest inValue = new Energistics.DataAccess.WITSML131.WMLP.WMLP_GetVersionRequest();
            Energistics.DataAccess.WITSML131.WMLP.WMLP_GetVersionResponse retVal = ((Energistics.DataAccess.WITSML131.WMLP.IWMLP)(this)).WMLP_GetVersion(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML131.WMLP.WMLP_SubscribeResponse Energistics.DataAccess.WITSML131.WMLP.IWMLP.WMLP_Subscribe(Energistics.DataAccess.WITSML131.WMLP.WMLP_SubscribeRequest request)
        {
            return base.Channel.WMLP_Subscribe(request);
        }
        
        public short WMLP_Subscribe(string SubscriptionIn, string OptionsIn, string CapabilitiesIn, out string SubscriptionOut, out string SuppMsgOut)
        {
            Energistics.DataAccess.WITSML131.WMLP.WMLP_SubscribeRequest inValue = new Energistics.DataAccess.WITSML131.WMLP.WMLP_SubscribeRequest();
            inValue.SubscriptionIn = SubscriptionIn;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            Energistics.DataAccess.WITSML131.WMLP.WMLP_SubscribeResponse retVal = ((Energistics.DataAccess.WITSML131.WMLP.IWMLP)(this)).WMLP_Subscribe(inValue);
            SubscriptionOut = retVal.SubscriptionOut;
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WMLP))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WMLP))
            {
                return new System.ServiceModel.EndpointAddress("http://yourorg.com/yourwebservice");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WMLP.GetBindingForEndpoint(EndpointConfiguration.WMLP);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WMLP.GetEndpointAddress(EndpointConfiguration.WMLP);
        }
        
        public enum EndpointConfiguration
        {
            
            WMLP,
        }
    }
}
