<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>PDS.WITSMLstudio.Store</RootNamespace>
    <AssemblyName>PDS.WITSMLstudio.Store.MongoDb</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\PDS.WITSMLstudio.Store.MongoDb.xml</DocumentationFile>
    <RunCodeAnalysis>false</RunCodeAnalysis>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\PDS.WITSMLstudio.Store.MongoDb.xml</DocumentationFile>
    <RunCodeAnalysis>true</RunCodeAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.ApplicationServices" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\External\GlobalAssemblyInfo.cs">
      <Link>GlobalAssemblyInfo.cs</Link>
    </Compile>
    <Compile Update="Data\Activities\Activity200DataAdapter.generated.cs">
      <DependentUpon>Activity200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ActivityTemplates\ActivityTemplate200DataAdapter.generated.cs">
      <DependentUpon>ActivityTemplate200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Attachments\Attachment141DataAdapter.generated.cs">
      <DependentUpon>Attachment141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Attachments\Attachment200DataAdapter.generated.cs">
      <DependentUpon>Attachment200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\BhaRuns\BhaRun131DataAdapter.generated.cs">
      <DependentUpon>BhaRun131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\BhaRuns\BhaRun141DataAdapter.generated.cs">
      <DependentUpon>BhaRun141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\BhaRuns\BhaRun200DataAdapter.generated.cs">
      <DependentUpon>BhaRun200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobEvaluations\CementJobEvaluation200DataAdapter.generated.cs">
      <DependentUpon>CementJobEvaluation200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobs\CementJob131DataAdapter.generated.cs">
      <DependentUpon>CementJob131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobs\CementJob141DataAdapter.generated.cs">
      <DependentUpon>CementJob141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobs\CementJob200DataAdapter.generated.cs">
      <DependentUpon>CementJob200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ChannelSets\ChannelSet200DataAdapter.generated.cs">
      <DependentUpon>ChannelSet200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Channels\Channel200DataAdapter.generated.cs">
      <DependentUpon>Channel200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ConvCores\ConvCore131DataAdapter.generated.cs">
      <DependentUpon>ConvCore131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ConvCores\ConvCore141DataAdapter.generated.cs">
      <DependentUpon>ConvCore141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DataAssuranceRecords\DataAssuranceRecord200DataAdapter.generated.cs">
      <DependentUpon>DataAssuranceRecord200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DepthRegImages\DepthRegImage141DataAdapter.generated.cs">
      <DependentUpon>DepthRegImage141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DepthRegImages\DepthRegImage200DataAdapter.generated.cs">
      <DependentUpon>DepthRegImage200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DownholeComponents\DownholeComponent141DataAdapter.generated.cs">
      <DependentUpon>DownholeComponent141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DownholeComponents\DownholeComponent200DataAdapter.generated.cs">
      <DependentUpon>DownholeComponent200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DrillReports\DrillReport141DataAdapter.generated.cs">
      <DependentUpon>DrillReport141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DrillReports\DrillReport200DataAdapter.generated.cs">
      <DependentUpon>DrillReport200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FluidsReports\FluidsReport131DataAdapter.generated.cs">
      <DependentUpon>FluidsReport131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FluidsReports\FluidsReport141DataAdapter.generated.cs">
      <DependentUpon>FluidsReport141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FluidsReports\FluidsReport200DataAdapter.generated.cs">
      <DependentUpon>FluidsReport200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FormationMarkers\FormationMarker131DataAdapter.generated.cs">
      <DependentUpon>FormationMarker131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FormationMarkers\FormationMarker141DataAdapter.generated.cs">
      <DependentUpon>FormationMarker141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Logs\Log131DataAdapter.generated.cs">
      <DependentUpon>Log131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Logs\Log141DataAdapter.generated.cs">
      <DependentUpon>Log141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Logs\Log200DataAdapter.generated.cs">
      <DependentUpon>Log200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Messages\Message131DataAdapter.generated.cs">
      <DependentUpon>Message131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Messages\Message141DataAdapter.generated.cs">
      <DependentUpon>Message141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MongoDbClassMapper.generated.cs">
      <DependentUpon>MongoDbClassMapper.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MudLogReports\MudLogReport200DataAdapter.generated.cs">
      <DependentUpon>MudLogReport200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MudLogs\MudLog131DataAdapter.generated.cs">
      <DependentUpon>MudLog131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MudLogs\MudLog141DataAdapter.generated.cs">
      <DependentUpon>MudLog141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\OpsReports\OpsReport131DataAdapter.generated.cs">
      <DependentUpon>OpsReport131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\OpsReports\OpsReport141DataAdapter.generated.cs">
      <DependentUpon>OpsReport141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\OpsReports\OpsReport200DataAdapter.generated.cs">
      <DependentUpon>OpsReport200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Rigs\Rig131DataAdapter.generated.cs">
      <DependentUpon>Rig131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Rigs\Rig141DataAdapter.generated.cs">
      <DependentUpon>Rig141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Rigs\Rig200DataAdapter.generated.cs">
      <DependentUpon>Rig200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\RigUtilizations\RigUtilization200DataAdapter.generated.cs">
      <DependentUpon>RigUtilization200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Risks\Risk131DataAdapter.generated.cs">
      <DependentUpon>Risk131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Risks\Risk141DataAdapter.generated.cs">
      <DependentUpon>Risk141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Risks\Risk200DataAdapter.generated.cs">
      <DependentUpon>Risk200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SidewallCores\SidewallCore131DataAdapter.generated.cs">
      <DependentUpon>SidewallCore131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SidewallCores\SidewallCore141DataAdapter.generated.cs">
      <DependentUpon>SidewallCore141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\StimJobStages\StimJobStage200DataAdapter.generated.cs">
      <DependentUpon>StimJobStage200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\StimJobs\StimJob141DataAdapter.generated.cs">
      <DependentUpon>StimJob141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\StimJobs\StimJob200DataAdapter.generated.cs">
      <DependentUpon>StimJob200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SurveyPrograms\SurveyProgram131DataAdapter.generated.cs">
      <DependentUpon>SurveyProgram131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SurveyPrograms\SurveyProgram141DataAdapter.generated.cs">
      <DependentUpon>SurveyProgram141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SurveyPrograms\SurveyProgram200DataAdapter.generated.cs">
      <DependentUpon>SurveyProgram200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Targets\Target131DataAdapter.generated.cs">
      <DependentUpon>Target131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Targets\Target141DataAdapter.generated.cs">
      <DependentUpon>Target141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Trajectories\Trajectory131DataAdapter.generated.cs">
      <DependentUpon>Trajectory131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Trajectories\Trajectory141DataAdapter.generated.cs">
      <DependentUpon>Trajectory141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Trajectories\Trajectory200DataAdapter.generated.cs">
      <DependentUpon>Trajectory200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Tubulars\Tubular131DataAdapter.generated.cs">
      <DependentUpon>Tubular131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Tubulars\Tubular141DataAdapter.generated.cs">
      <DependentUpon>Tubular141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Tubulars\Tubular200DataAdapter.generated.cs">
      <DependentUpon>Tubular200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WbGeometries\WbGeometry131DataAdapter.generated.cs">
      <DependentUpon>WbGeometry131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WbGeometries\WbGeometry141DataAdapter.generated.cs">
      <DependentUpon>WbGeometry141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreCompletions\WellboreCompletion141DataAdapter.generated.cs">
      <DependentUpon>WellboreCompletion141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreCompletions\WellboreCompletion200DataAdapter.generated.cs">
      <DependentUpon>WellboreCompletion200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreGeologies\WellboreGeology200DataAdapter.generated.cs">
      <DependentUpon>WellboreGeology200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreGeometries\WellboreGeometry200DataAdapter.generated.cs">
      <DependentUpon>WellboreGeometry200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreMarkerSets\WellboreMarkerSet200DataAdapter.generated.cs">
      <DependentUpon>WellboreMarkerSet200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreMarkers\WellboreMarker200DataAdapter.generated.cs">
      <DependentUpon>WellboreMarker200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wellbores\Wellbore131DataAdapter.generated.cs">
      <DependentUpon>Wellbore131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wellbores\Wellbore141DataAdapter.generated.cs">
      <DependentUpon>Wellbore141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wellbores\Wellbore200DataAdapter.generated.cs">
      <DependentUpon>Wellbore200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCMLedgers\WellCMLedger141DataAdapter.generated.cs">
      <DependentUpon>WellCMLedger141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCMLedgers\WellCMLedger200DataAdapter.generated.cs">
      <DependentUpon>WellCMLedger200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCompletions\WellCompletion141DataAdapter.generated.cs">
      <DependentUpon>WellCompletion141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCompletions\WellCompletion200DataAdapter.generated.cs">
      <DependentUpon>WellCompletion200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellLogs\WellLog131DataAdapter.generated.cs">
      <DependentUpon>WellLog131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wells\Well131DataAdapter.generated.cs">
      <DependentUpon>Well131DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wells\Well141DataAdapter.generated.cs">
      <DependentUpon>Well141DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wells\Well200DataAdapter.generated.cs">
      <DependentUpon>Well200DataAdapter.cs</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
      <CustomToolNamespace>PDS.WITSMLstudio.Store.MongoDb</CustomToolNamespace>
      <SubType>Designer</SubType>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess.PRODML\DataAccess.PRODML.csproj" />
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess.RESQML\DataAccess.RESQML.csproj" />
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess.WITSML\DataAccess.WITSML.csproj" />
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\..\ext\etp-devkit\ext\etp.net\src\ETP.Messages\ETP.Messages.csproj" />
    <ProjectReference Include="..\..\ext\etp-devkit\src\DevKit\DevKit.csproj" />
    <ProjectReference Include="..\Framework\Framework.csproj" />
    <ProjectReference Include="..\Store.Core\Store.Core.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Store.MongoDb.Common\Store.MongoDb.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Antlr" Version="3.5.0.2" />
    <PackageReference Include="Apache.Avro" Version="1.12.0" />
    <PackageReference Include="LinqToQuerystring" Version="0.7.0.8" />
    <PackageReference Include="log4net" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.WebHost" Version="5.3.0" />
    <PackageReference Include="Microsoft.Web.Infrastructure" Version="2.0.0" />
    <PackageReference Include="MongoDB.Bson" Version="3.4.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.4.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Snappy.NET" Version="1.1.1.8" />
    <PackageReference Include="SuperSocket.ClientEngine.Core" Version="0.10.0" />
    <PackageReference Include="SuperWebSocket" Version="0.9.0.2" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="9.0.7" />
    <PackageReference Include="System.Runtime.InteropServices.RuntimeInformation" Version="4.3.0" />
    <PackageReference Include="WebSocket4Net" Version="0.15.2" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Data\Realtimes\Realtime131DataAdapter.cs" />
    <Compile Remove="Data\Realtimes\Realtime131DataAdapter.generated.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel141DataAdapter.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel141DataAdapter.generated.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel200DataAdapter.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel200DataAdapter.generated.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet141DataAdapter.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet141DataAdapter.generated.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet200DataAdapter.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet200DataAdapter.generated.cs" />
    <Compile Remove="Data\TrajectoryStations\TrajectoryStation200DataAdapter.cs" />
    <Compile Remove="Data\TrajectoryStations\TrajectoryStation200DataAdapter.generated.cs" />
  </ItemGroup>
  <PropertyGroup />
  <PropertyGroup />
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>