//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторного создания кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Energistics.DataAccess.WITSML141.WMLS
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.witsml.org/wsdl/120", ConfigurationName="Energistics.DataAccess.WITSML141.WMLS.StoreSoapPort")]
    public interface IWMLS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_AddToStore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_AddToStoreResponse WMLS_AddToStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_AddToStoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_DeleteFromStore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_DeleteFromStoreResponse WMLS_DeleteFromStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_DeleteFromStoreRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как пространство имен упаковщика (http://www.witsml.org/message/120) сообщения WMLS_GetBaseMsgRequest не соответствует значению по умолчанию (http://www.witsml.org/wsdl/120).
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetBaseMsg", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetBaseMsgResponse WMLS_GetBaseMsg(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetBaseMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetCap", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetCapResponse WMLS_GetCap(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetCapRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetFromStore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetFromStoreResponse WMLS_GetFromStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetFromStoreRequest request);
        
        // CODEGEN: Создание контракта сообщения, так как пространство имен упаковщика (http://www.witsml.org/message/120) сообщения WMLS_GetVersionRequest не соответствует значению по умолчанию (http://www.witsml.org/wsdl/120).
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_GetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetVersionResponse WMLS_GetVersion(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetVersionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.witsml.org/action/120/Store.WMLS_UpdateInStore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_UpdateInStoreResponse WMLS_UpdateInStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_UpdateInStoreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_AddToStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_AddToStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_AddToStoreRequest()
        {
        }
        
        public WMLS_AddToStoreRequest(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.XMLin = XMLin;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_AddToStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_AddToStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SuppMsgOut;
        
        public WMLS_AddToStoreResponse()
        {
        }
        
        public WMLS_AddToStoreResponse(short Result, string SuppMsgOut)
        {
            this.Result = Result;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_DeleteFromStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_DeleteFromStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string QueryIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_DeleteFromStoreRequest()
        {
        }
        
        public WMLS_DeleteFromStoreRequest(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.QueryIn = QueryIn;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_DeleteFromStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_DeleteFromStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SuppMsgOut;
        
        public WMLS_DeleteFromStoreResponse()
        {
        }
        
        public WMLS_DeleteFromStoreResponse(short Result, string SuppMsgOut)
        {
            this.Result = Result;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetBaseMsg", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetBaseMsgRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short ReturnValueIn;
        
        public WMLS_GetBaseMsgRequest()
        {
        }
        
        public WMLS_GetBaseMsgRequest(short ReturnValueIn)
        {
            this.ReturnValueIn = ReturnValueIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetBaseMsgResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetBaseMsgResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public WMLS_GetBaseMsgResponse()
        {
        }
        
        public WMLS_GetBaseMsgResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetCap", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetCapRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string OptionsIn;
        
        public WMLS_GetCapRequest()
        {
        }
        
        public WMLS_GetCapRequest(string OptionsIn)
        {
            this.OptionsIn = OptionsIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetCapResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetCapResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string CapabilitiesOut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SuppMsgOut;
        
        public WMLS_GetCapResponse()
        {
        }
        
        public WMLS_GetCapResponse(short Result, string CapabilitiesOut, string SuppMsgOut)
        {
            this.Result = Result;
            this.CapabilitiesOut = CapabilitiesOut;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetFromStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetFromStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string QueryIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_GetFromStoreRequest()
        {
        }
        
        public WMLS_GetFromStoreRequest(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.QueryIn = QueryIn;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetFromStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetFromStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLout;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string SuppMsgOut;
        
        public WMLS_GetFromStoreResponse()
        {
        }
        
        public WMLS_GetFromStoreResponse(short Result, string XMLout, string SuppMsgOut)
        {
            this.Result = Result;
            this.XMLout = XMLout;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetVersion", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetVersionRequest
    {
        
        public WMLS_GetVersionRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_GetVersionResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_GetVersionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string Result;
        
        public WMLS_GetVersionResponse()
        {
        }
        
        public WMLS_GetVersionResponse(string Result)
        {
            this.Result = Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_UpdateInStore", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_UpdateInStoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string WMLtypeIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string XMLin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string OptionsIn;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public string CapabilitiesIn;
        
        public WMLS_UpdateInStoreRequest()
        {
        }
        
        public WMLS_UpdateInStoreRequest(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn)
        {
            this.WMLtypeIn = WMLtypeIn;
            this.XMLin = XMLin;
            this.OptionsIn = OptionsIn;
            this.CapabilitiesIn = CapabilitiesIn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="WMLS_UpdateInStoreResponse", WrapperNamespace="http://www.witsml.org/message/120", IsWrapped=true)]
    public partial class WMLS_UpdateInStoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public short Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string SuppMsgOut;
        
        public WMLS_UpdateInStoreResponse()
        {
        }
        
        public WMLS_UpdateInStoreResponse(short Result, string SuppMsgOut)
        {
            this.Result = Result;
            this.SuppMsgOut = SuppMsgOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface StoreSoapPortChannel : Energistics.DataAccess.WITSML141.WMLS.IWMLS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class WMLS : System.ServiceModel.ClientBase<Energistics.DataAccess.WITSML141.WMLS.IWMLS>, Energistics.DataAccess.WITSML141.WMLS.IWMLS
    {
        
        /// <summary>
        /// Реализуйте этот разделяемый метод для настройки конечной точки службы.
        /// </summary>
        /// <param name="serviceEndpoint">Настраиваемая конечная точка</param>
        /// <param name="clientCredentials">Учетные данные клиента.</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WMLS() : 
                base(WMLS.GetDefaultBinding(), WMLS.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WMLS.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLS(EndpointConfiguration endpointConfiguration) : 
                base(WMLS.GetBindingForEndpoint(endpointConfiguration), WMLS.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLS(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WMLS.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLS(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WMLS.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WMLS(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_AddToStoreResponse Energistics.DataAccess.WITSML141.WMLS.IWMLS.WMLS_AddToStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_AddToStoreRequest request)
        {
            return base.Channel.WMLS_AddToStore(request);
        }
        
        public short WMLS_AddToStore(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn, out string SuppMsgOut)
        {
            Energistics.DataAccess.WITSML141.WMLS.WMLS_AddToStoreRequest inValue = new Energistics.DataAccess.WITSML141.WMLS.WMLS_AddToStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.XMLin = XMLin;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            Energistics.DataAccess.WITSML141.WMLS.WMLS_AddToStoreResponse retVal = ((Energistics.DataAccess.WITSML141.WMLS.IWMLS)(this)).WMLS_AddToStore(inValue);
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_DeleteFromStoreResponse Energistics.DataAccess.WITSML141.WMLS.IWMLS.WMLS_DeleteFromStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_DeleteFromStoreRequest request)
        {
            return base.Channel.WMLS_DeleteFromStore(request);
        }
        
        public short WMLS_DeleteFromStore(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn, out string SuppMsgOut)
        {
            Energistics.DataAccess.WITSML141.WMLS.WMLS_DeleteFromStoreRequest inValue = new Energistics.DataAccess.WITSML141.WMLS.WMLS_DeleteFromStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.QueryIn = QueryIn;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            Energistics.DataAccess.WITSML141.WMLS.WMLS_DeleteFromStoreResponse retVal = ((Energistics.DataAccess.WITSML141.WMLS.IWMLS)(this)).WMLS_DeleteFromStore(inValue);
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetBaseMsgResponse Energistics.DataAccess.WITSML141.WMLS.IWMLS.WMLS_GetBaseMsg(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetBaseMsgRequest request)
        {
            return base.Channel.WMLS_GetBaseMsg(request);
        }
        
        public string WMLS_GetBaseMsg(short ReturnValueIn)
        {
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetBaseMsgRequest inValue = new Energistics.DataAccess.WITSML141.WMLS.WMLS_GetBaseMsgRequest();
            inValue.ReturnValueIn = ReturnValueIn;
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetBaseMsgResponse retVal = ((Energistics.DataAccess.WITSML141.WMLS.IWMLS)(this)).WMLS_GetBaseMsg(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetCapResponse Energistics.DataAccess.WITSML141.WMLS.IWMLS.WMLS_GetCap(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetCapRequest request)
        {
            return base.Channel.WMLS_GetCap(request);
        }
        
        public short WMLS_GetCap(string OptionsIn, out string CapabilitiesOut, out string SuppMsgOut)
        {
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetCapRequest inValue = new Energistics.DataAccess.WITSML141.WMLS.WMLS_GetCapRequest();
            inValue.OptionsIn = OptionsIn;
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetCapResponse retVal = ((Energistics.DataAccess.WITSML141.WMLS.IWMLS)(this)).WMLS_GetCap(inValue);
            CapabilitiesOut = retVal.CapabilitiesOut;
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetFromStoreResponse Energistics.DataAccess.WITSML141.WMLS.IWMLS.WMLS_GetFromStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetFromStoreRequest request)
        {
            return base.Channel.WMLS_GetFromStore(request);
        }
        
        public short WMLS_GetFromStore(string WMLtypeIn, string QueryIn, string OptionsIn, string CapabilitiesIn, out string XMLout, out string SuppMsgOut)
        {
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetFromStoreRequest inValue = new Energistics.DataAccess.WITSML141.WMLS.WMLS_GetFromStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.QueryIn = QueryIn;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetFromStoreResponse retVal = ((Energistics.DataAccess.WITSML141.WMLS.IWMLS)(this)).WMLS_GetFromStore(inValue);
            XMLout = retVal.XMLout;
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_GetVersionResponse Energistics.DataAccess.WITSML141.WMLS.IWMLS.WMLS_GetVersion(Energistics.DataAccess.WITSML141.WMLS.WMLS_GetVersionRequest request)
        {
            return base.Channel.WMLS_GetVersion(request);
        }
        
        public string WMLS_GetVersion()
        {
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetVersionRequest inValue = new Energistics.DataAccess.WITSML141.WMLS.WMLS_GetVersionRequest();
            Energistics.DataAccess.WITSML141.WMLS.WMLS_GetVersionResponse retVal = ((Energistics.DataAccess.WITSML141.WMLS.IWMLS)(this)).WMLS_GetVersion(inValue);
            return retVal.Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Energistics.DataAccess.WITSML141.WMLS.WMLS_UpdateInStoreResponse Energistics.DataAccess.WITSML141.WMLS.IWMLS.WMLS_UpdateInStore(Energistics.DataAccess.WITSML141.WMLS.WMLS_UpdateInStoreRequest request)
        {
            return base.Channel.WMLS_UpdateInStore(request);
        }
        
        public short WMLS_UpdateInStore(string WMLtypeIn, string XMLin, string OptionsIn, string CapabilitiesIn, out string SuppMsgOut)
        {
            Energistics.DataAccess.WITSML141.WMLS.WMLS_UpdateInStoreRequest inValue = new Energistics.DataAccess.WITSML141.WMLS.WMLS_UpdateInStoreRequest();
            inValue.WMLtypeIn = WMLtypeIn;
            inValue.XMLin = XMLin;
            inValue.OptionsIn = OptionsIn;
            inValue.CapabilitiesIn = CapabilitiesIn;
            Energistics.DataAccess.WITSML141.WMLS.WMLS_UpdateInStoreResponse retVal = ((Energistics.DataAccess.WITSML141.WMLS.IWMLS)(this)).WMLS_UpdateInStore(inValue);
            SuppMsgOut = retVal.SuppMsgOut;
            return retVal.Result;
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WMLS))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WMLS))
            {
                return new System.ServiceModel.EndpointAddress("http://yourorg.com/yourwebservice");
            }
            throw new System.InvalidOperationException(string.Format("Не удалось найти конечную точку с именем \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WMLS.GetBindingForEndpoint(EndpointConfiguration.WMLS);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WMLS.GetEndpointAddress(EndpointConfiguration.WMLS);
        }
        
        public enum EndpointConfiguration
        {
            
            WMLS,
        }
    }
}
