<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>PDS.WITSMLstudio</RootNamespace>
    <AssemblyName>PDS.WITSMLstudio.Core</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <DocumentationFile>bin\Debug\PDS.WITSMLstudio.Core.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\PDS.WITSMLstudio.Core.xml</DocumentationFile>
    <RunCodeAnalysis>false</RunCodeAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Services" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\External\GlobalAssemblyInfo.cs">
      <Link>GlobalAssemblyInfo.cs</Link>
    </Compile>
    <Compile Update="ObjectNames.generated.cs">
      <DependentUpon>ObjectNames.cs</DependentUpon>
    </Compile>
    <Compile Update="ObjectTypes.generated.cs">
      <DependentUpon>ObjectTypes.cs</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
    <Compile Update="Query\QueryTemplates.generated.cs">
      <DependentUpon>QueryTemplates.cs</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess.PRODML\DataAccess.PRODML.csproj" />
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess.RESQML\DataAccess.RESQML.csproj" />
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess.WITSML\DataAccess.WITSML.csproj" />
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\..\ext\etp-devkit\ext\etp.net\src\ETP.Messages\ETP.Messages.csproj" />
    <ProjectReference Include="..\..\ext\etp-devkit\src\DevKit\DevKit.csproj" />
    <ProjectReference Include="..\Framework\Framework.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Apache.Avro" Version="1.12.0" />
    <PackageReference Include="FluentValidationNA" Version="1.2.16" />
    <PackageReference Include="LinqExtender" Version="3.0.1" />
    <PackageReference Include="log4net" Version="3.1.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="SuperSocket.ClientEngine.Core" Version="0.10.0" />
    <PackageReference Include="SuperWebSocket" Version="0.9.0.2" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.ComponentModel.Composition" Version="9.0.7" />
    <PackageReference Include="System.Linq.Dynamic.Library" Version="1.1.14" />
    <PackageReference Include="WebSocket4Net" Version="0.15.2" />
  </ItemGroup>
  <PropertyGroup />
  <PropertyGroup />
</Project>