<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>PDS.WITSMLstudio.Store</RootNamespace>
    <AssemblyName>PDS.WITSMLstudio.Store.Core</AssemblyName>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>false</ImplicitUsings>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <RunCodeAnalysis>false</RunCodeAnalysis>
    <DocumentationFile>bin\Debug\PDS.WITSMLstudio.Store.Core.xml</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\PDS.WITSMLstudio.Store.Core.xml</DocumentationFile>
    <RunCodeAnalysis>true</RunCodeAnalysis>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="9.0.7" />
    <PackageReference Include="Fare" Version="2.2.1" />
    <PackageReference Include="SuperSocket.ClientEngine.Core" Version="0.10.0" />
    <PackageReference Include="SuperWebSocket" Version="0.9.0.2" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.7" />
    <PackageReference Include="WebSocket4Net" Version="0.15.2" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="2.0.0" />
    <PackageReference Include="CoreWCF.Primitives" Version="1.8.0" />
    <PackageReference Include="CoreWCF.ConfigurationManager" Version="1.8.0" />
    <PackageReference Include="CoreWCF.Http" Version="1.8.0" />
    <PackageReference Include="CoreWCF.WebHttp" Version="1.8.0" />
    <PackageReference Include="CoreWCF.NetTcp" Version="1.8.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\External\GlobalAssemblyInfo.cs">
      <Link>GlobalAssemblyInfo.cs</Link>
    </Compile>
    <Compile Update="Data\Attachments\Attachment141DataProvider.generated.cs">
      <DependentUpon>Attachment141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Attachments\Attachment141Validator.generated.cs">
      <DependentUpon>Attachment141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\BhaRuns\BhaRun131DataProvider.generated.cs">
      <DependentUpon>BhaRun131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\BhaRuns\BhaRun131Validator.generated.cs">
      <DependentUpon>BhaRun131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\BhaRuns\BhaRun141DataProvider.generated.cs">
      <DependentUpon>BhaRun141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\BhaRuns\BhaRun141Validator.generated.cs">
      <DependentUpon>BhaRun141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobs\CementJob131DataProvider.generated.cs">
      <DependentUpon>CementJob131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobs\CementJob131Validator.generated.cs">
      <DependentUpon>CementJob131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobs\CementJob141DataProvider.generated.cs">
      <DependentUpon>CementJob141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\CementJobs\CementJob141Validator.generated.cs">
      <DependentUpon>CementJob141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ConvCores\ConvCore131DataProvider.generated.cs">
      <DependentUpon>ConvCore131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ConvCores\ConvCore131Validator.generated.cs">
      <DependentUpon>ConvCore131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ConvCores\ConvCore141DataProvider.generated.cs">
      <DependentUpon>ConvCore141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\ConvCores\ConvCore141Validator.generated.cs">
      <DependentUpon>ConvCore141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DepthRegImages\DepthRegImage141DataProvider.generated.cs">
      <DependentUpon>DepthRegImage141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DepthRegImages\DepthRegImage141Validator.generated.cs">
      <DependentUpon>DepthRegImage141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DownholeComponents\DownholeComponent141DataProvider.generated.cs">
      <DependentUpon>DownholeComponent141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DownholeComponents\DownholeComponent141Validator.generated.cs">
      <DependentUpon>DownholeComponent141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DrillReports\DrillReport141DataProvider.generated.cs">
      <DependentUpon>DrillReport141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\DrillReports\DrillReport141Validator.generated.cs">
      <DependentUpon>DrillReport141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FluidsReports\FluidsReport131DataProvider.generated.cs">
      <DependentUpon>FluidsReport131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FluidsReports\FluidsReport131Validator.generated.cs">
      <DependentUpon>FluidsReport131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FluidsReports\FluidsReport141DataProvider.generated.cs">
      <DependentUpon>FluidsReport141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FluidsReports\FluidsReport141Validator.generated.cs">
      <DependentUpon>FluidsReport141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FormationMarkers\FormationMarker131DataProvider.generated.cs">
      <DependentUpon>FormationMarker131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FormationMarkers\FormationMarker131Validator.generated.cs">
      <DependentUpon>FormationMarker131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FormationMarkers\FormationMarker141DataProvider.generated.cs">
      <DependentUpon>FormationMarker141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\FormationMarkers\FormationMarker141Validator.generated.cs">
      <DependentUpon>FormationMarker141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Logs\Log131DataProvider.generated.cs">
      <DependentUpon>Log131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Logs\Log131Validator.generated.cs">
      <DependentUpon>Log131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Logs\Log141DataProvider.generated.cs">
      <DependentUpon>Log141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Logs\Log141Validator.generated.cs">
      <DependentUpon>Log141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Messages\Message131DataProvider.generated.cs">
      <DependentUpon>Message131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Messages\Message131Validator.generated.cs">
      <DependentUpon>Message131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Messages\Message141DataProvider.generated.cs">
      <DependentUpon>Message141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Messages\Message141Validator.generated.cs">
      <DependentUpon>Message141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MudLogs\MudLog131DataProvider.generated.cs">
      <DependentUpon>MudLog131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MudLogs\MudLog131Validator.generated.cs">
      <DependentUpon>MudLog131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MudLogs\MudLog141DataProvider.generated.cs">
      <DependentUpon>MudLog141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\MudLogs\MudLog141Validator.generated.cs">
      <DependentUpon>MudLog141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\OpsReports\OpsReport131DataProvider.generated.cs">
      <DependentUpon>OpsReport131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\OpsReports\OpsReport131Validator.generated.cs">
      <DependentUpon>OpsReport131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\OpsReports\OpsReport141DataProvider.generated.cs">
      <DependentUpon>OpsReport141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\OpsReports\OpsReport141Validator.generated.cs">
      <DependentUpon>OpsReport141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Rigs\Rig131DataProvider.generated.cs">
      <DependentUpon>Rig131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Rigs\Rig131Validator.generated.cs">
      <DependentUpon>Rig131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Rigs\Rig141DataProvider.generated.cs">
      <DependentUpon>Rig141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Rigs\Rig141Validator.generated.cs">
      <DependentUpon>Rig141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Risks\Risk131DataProvider.generated.cs">
      <DependentUpon>Risk131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Risks\Risk131Validator.generated.cs">
      <DependentUpon>Risk131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Risks\Risk141DataProvider.generated.cs">
      <DependentUpon>Risk141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Risks\Risk141Validator.generated.cs">
      <DependentUpon>Risk141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SidewallCores\SidewallCore131DataProvider.generated.cs">
      <DependentUpon>SidewallCore131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SidewallCores\SidewallCore131Validator.generated.cs">
      <DependentUpon>SidewallCore131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SidewallCores\SidewallCore141DataProvider.generated.cs">
      <DependentUpon>SidewallCore141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SidewallCores\SidewallCore141Validator.generated.cs">
      <DependentUpon>SidewallCore141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\StimJobs\StimJob141DataProvider.generated.cs">
      <DependentUpon>StimJob141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\StimJobs\StimJob141Validator.generated.cs">
      <DependentUpon>StimJob141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SurveyPrograms\SurveyProgram131DataProvider.generated.cs">
      <DependentUpon>SurveyProgram131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SurveyPrograms\SurveyProgram131Validator.generated.cs">
      <DependentUpon>SurveyProgram131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SurveyPrograms\SurveyProgram141DataProvider.generated.cs">
      <DependentUpon>SurveyProgram141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\SurveyPrograms\SurveyProgram141Validator.generated.cs">
      <DependentUpon>SurveyProgram141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Targets\Target131DataProvider.generated.cs">
      <DependentUpon>Target131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Targets\Target131Validator.generated.cs">
      <DependentUpon>Target131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Targets\Target141DataProvider.generated.cs">
      <DependentUpon>Target141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Targets\Target141Validator.generated.cs">
      <DependentUpon>Target141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Trajectories\Trajectory131DataProvider.generated.cs">
      <DependentUpon>Trajectory131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Trajectories\Trajectory131Validator.generated.cs">
      <DependentUpon>Trajectory131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Trajectories\Trajectory141DataProvider.generated.cs">
      <DependentUpon>Trajectory141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Trajectories\Trajectory141Validator.generated.cs">
      <DependentUpon>Trajectory141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Tubulars\Tubular131DataProvider.generated.cs">
      <DependentUpon>Tubular131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Tubulars\Tubular131Validator.generated.cs">
      <DependentUpon>Tubular131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Tubulars\Tubular141DataProvider.generated.cs">
      <DependentUpon>Tubular141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Tubulars\Tubular141Validator.generated.cs">
      <DependentUpon>Tubular141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WbGeometries\WbGeometry131DataProvider.generated.cs">
      <DependentUpon>WbGeometry131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WbGeometries\WbGeometry131Validator.generated.cs">
      <DependentUpon>WbGeometry131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WbGeometries\WbGeometry141DataProvider.generated.cs">
      <DependentUpon>WbGeometry141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WbGeometries\WbGeometry141Validator.generated.cs">
      <DependentUpon>WbGeometry141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreCompletions\WellboreCompletion141DataProvider.generated.cs">
      <DependentUpon>WellboreCompletion141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellboreCompletions\WellboreCompletion141Validator.generated.cs">
      <DependentUpon>WellboreCompletion141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wellbores\Wellbore131DataProvider.generated.cs">
      <DependentUpon>Wellbore131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wellbores\Wellbore131Validator.generated.cs">
      <DependentUpon>Wellbore131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wellbores\Wellbore141DataProvider.generated.cs">
      <DependentUpon>Wellbore141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wellbores\Wellbore141Validator.generated.cs">
      <DependentUpon>Wellbore141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCMLedgers\WellCMLedger141DataProvider.generated.cs">
      <DependentUpon>WellCMLedger141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCMLedgers\WellCMLedger141Validator.generated.cs">
      <DependentUpon>WellCMLedger141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCompletions\WellCompletion141DataProvider.generated.cs">
      <DependentUpon>WellCompletion141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellCompletions\WellCompletion141Validator.generated.cs">
      <DependentUpon>WellCompletion141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellLogs\WellLog131DataProvider.generated.cs">
      <DependentUpon>WellLog131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\WellLogs\WellLog131Validator.generated.cs">
      <DependentUpon>WellLog131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wells\Well131DataProvider.generated.cs">
      <DependentUpon>Well131DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wells\Well131Validator.generated.cs">
      <DependentUpon>Well131Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wells\Well141DataProvider.generated.cs">
      <DependentUpon>Well141DataProvider.cs</DependentUpon>
    </Compile>
    <Compile Update="Data\Wells\Well141Validator.generated.cs">
      <DependentUpon>Well141Validator.cs</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess.WITSML\DataAccess.WITSML.csproj" />
    <ProjectReference Include="..\..\ext\devkit-c\source\DevKitGenerator\DataAccess\DataAccess.csproj" />
    <ProjectReference Include="..\..\ext\etp-devkit\ext\etp.net\src\ETP.Messages\ETP.Messages.csproj" />
    <ProjectReference Include="..\..\ext\etp-devkit\src\DevKit\DevKit.csproj" />
    <ProjectReference Include="..\Framework\Framework.csproj" />
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Data\MultiCastDataAdapter.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel141DataProvider.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel141DataProvider.generated.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel141Validator.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel141Validator.generated.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel200DataProvider.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel200DataProvider.generated.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel200Validator.cs" />
    <Compile Remove="Data\ToolErrorModels\ToolErrorModel200Validator.generated.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet141DataProvider.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet141DataProvider.generated.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet141Validator.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet141Validator.generated.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet200DataProvider.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet200DataProvider.generated.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet200Validator.cs" />
    <Compile Remove="Data\ToolErrorTermSets\ToolErrorTermSet200Validator.generated.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Data\ChannelSets\" />
  </ItemGroup>
</Project>