<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Platform Condition=" '$(Platform)' == '' ">x86</Platform>
    <OutputType>Exe</OutputType>
    <RootNamespace>Energistics.SchemaGatherer</RootNamespace>
    <AssemblyName>Energistics.SchemaGatherer</AssemblyName>
    <SccProjectName></SccProjectName>
    <SccLocalPath></SccLocalPath>
    <SccAuxPath></SccAuxPath>
    <SccProvider></SccProvider>
    <!--<UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>-->
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Debug|AnyCPU'">
    <LangVersion>default</LangVersion>
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|AnyCPU'">
    <CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.XmlSerializer.Generator" Version="9.0.8" />
    <PackageReference Include="Mono.Options" Version="5.3.0.1" />
    <PackageReference Include="System.CodeDom" Version="8.0.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.8" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\DataAccess\ExtensibleEnum.cs">
      <Link>ExtensibleEnum.cs</Link>
    </Compile>
    <Compile Include="..\DataAccess\Reflection\EnergisticsDataTypeAttribute.cs">
      <Link>EnergisticsDataTypeAttribute.cs</Link>
    </Compile>
    <Compile Include="..\DataAccess\Timestamp.cs">
      <Link>Timestamp.cs</Link>
    </Compile>
  </ItemGroup>
</Project>